// composables/useProducts.ts
export interface Product {
  id: number
  name: string
  nameEn: string
  origin: string
  tagline: string
  description: string
  pricePerKg: number
  category: 'عربي فاخر' | 'إسبريسو' | 'تركي' | 'مختص'
  roast: 'فاتح' | 'متوسط' | 'داكن'
  notes: string[]
  gradient: string
  accent: string
  badge?: string
  image: string // SVG illustration path
}

export const useProducts = () => {
  const products: Product[] = [
    {
      id: 1,
      name: 'بن إثيوبي يرغاشيف',
      nameEn: 'Ethiopian Yirgacheffe',
      origin: 'إثيوبيا',
      tagline: 'حمضي مع لمسة من الفواكه',
      description: 'حبوب إثيوبية أصلية بنكهات الفاكهة الاستوائية ولمسة من الياسمين، محمصة تحميصاً متوسطاً للاستمتاع بأرقى تجربة قهوة.',
      pricePerKg: 1200,
      category: 'عربي فاخر',
      roast: 'متوسط',
      notes: ['فواكه', 'ياسمين', 'حمضي مشرق'],
      gradient: 'linear-gradient(135deg, #B5A986 0%, #514B3B 100%)',
      accent: '#A99768',
      badge: 'الأكثر مبيعاً',
      image: 'yirgacheffe',
    },
    {
      id: 2,
      name: 'بن يمني مطري',
      nameEn: 'Yemeni Mattari',
      origin: 'اليمن',
      tagline: 'قهوة الملوك والسلاطين',
      description: 'أرقى أنواع البن اليمني المطري من جبال اليمن الشاهقة، نكهة عميقة وقوام كريمي يأخذك لرحلة عبر التاريخ.',
      pricePerKg: 1800,
      category: 'عربي فاخر',
      roast: 'متوسط',
      notes: ['شوكولاتة', 'توابل', 'قوام كثيف'],
      gradient: 'linear-gradient(135deg, #514B3B 0%, #17140F 100%)',
      accent: '#C4B383',
      badge: 'فاخر',
      image: 'mattari',
    },
    {
      id: 3,
      name: 'بن برازيلي سانتوس',
      nameEn: 'Brazilian Santos',
      origin: 'البرازيل',
      tagline: 'مكسرات وكراميل',
      description: 'قاعدة مثالية للإسبريسو، نكهة بندق وكراميل بحموضة منخفضة، تمنحك كوب قهوة متكامل النكهة.',
      pricePerKg: 850,
      category: 'إسبريسو',
      roast: 'متوسط',
      notes: ['مكسرات', 'كراميل', 'لطيف'],
      gradient: 'linear-gradient(135deg, #A99B7C 0%, #514B3B 100%)',
      accent: '#8F7A49',
      image: 'santos',
    },
    {
      id: 4,
      name: 'بن كولومبي سوبريمو',
      nameEn: 'Colombian Supremo',
      origin: 'كولومبيا',
      tagline: 'متوازن وعطري',
      description: 'بن كولومبي عالي الجودة من جبال الأنديز بنكهة متوازنة وعبق فريد يأسر الحواس.',
      pricePerKg: 950,
      category: 'إسبريسو',
      roast: 'متوسط',
      notes: ['متوازن', 'حلو', 'عطري'],
      gradient: 'linear-gradient(135deg, #706A52 0%, #27231B 100%)',
      accent: '#A99768',
      image: 'supremo',
    },
    {
      id: 5,
      name: 'بن تركي مع الهيل',
      nameEn: 'Turkish with Cardamom',
      origin: 'تركيا',
      tagline: 'الأصيل بنكهة الهيل',
      description: 'بن تركي تقليدي مطحون ناعماً مع الهيل والمستكة لمذاق أصيل يعيدك لزمن الأسلاف.',
      pricePerKg: 1100,
      category: 'تركي',
      roast: 'داكن',
      notes: ['هيل', 'مستكة', 'تقليدي'],
      gradient: 'linear-gradient(135deg, #383328 0%, #0C0A07 100%)',
      accent: '#C4B383',
      image: 'turkish',
    },
    {
      id: 6,
      name: 'بن سعودي بالزعفران',
      nameEn: 'Saudi with Saffron',
      origin: 'السعودية',
      tagline: 'القهوة العربية الأصيلة',
      description: 'قهوة عربية فاتحة محمصة بطريقة تقليدية مع الزعفران والهيل والقرنفل، مذاق ضيافة العرب الأصيلة.',
      pricePerKg: 1400,
      category: 'عربي فاخر',
      roast: 'فاتح',
      notes: ['زعفران', 'هيل', 'قرنفل'],
      gradient: 'linear-gradient(135deg, #A99768 0%, #706A52 100%)',
      accent: '#8F7A49',
      badge: 'تقليدي',
      image: 'saudi',
    },
    {
      id: 7,
      name: 'بن كيني AA',
      nameEn: 'Kenyan AA',
      origin: 'كينيا',
      tagline: 'حمضي وفاكهي مشرق',
      description: 'حبوب كينية درجة AA الفاخرة بنكهات التوت الأسود والحمضيات وعمق رائع في الكوب.',
      pricePerKg: 1300,
      category: 'مختص',
      roast: 'متوسط',
      notes: ['توت', 'حمضي', 'مشرق'],
      gradient: 'linear-gradient(135deg, #706A52 0%, #383328 100%)',
      accent: '#A99768',
      image: 'kenya',
    },
    {
      id: 8,
      name: 'بن جواتيمالي أنتيغوا',
      nameEn: 'Guatemalan Antigua',
      origin: 'جواتيمالا',
      tagline: 'شوكولاتة داكنة',
      description: 'نكهات الشوكولاتة الداكنة والكراميل المحروق من مرتفعات أنتيغوا البركانية.',
      pricePerKg: 1050,
      category: 'مختص',
      roast: 'داكن',
      notes: ['شوكولاتة', 'دخاني', 'غني'],
      gradient: 'linear-gradient(135deg, #514B3B 0%, #17140F 100%)',
      accent: '#8F7A49',
      image: 'guatemala',
    },
    {
      id: 9,
      name: 'فرنسي محمص',
      nameEn: 'French Roast',
      origin: 'مزيج فاخر',
      tagline: 'تحميص داكن للقهوة القوية',
      description: 'مزيج محمص تحميصاً داكناً لمحبي القهوة القوية، قوام كثيف ونكهة دخانية مميزة.',
      pricePerKg: 780,
      category: 'إسبريسو',
      roast: 'داكن',
      notes: ['داكن', 'دخاني', 'قوي'],
      gradient: 'linear-gradient(135deg, #27231B 0%, #0C0A07 100%)',
      accent: '#C4B383',
      image: 'french',
    },
    {
      id: 10,
      name: 'بن مكسيكي عضوي',
      nameEn: 'Organic Mexican',
      origin: 'المكسيك',
      tagline: 'عضوي ١٠٠٪',
      description: 'حبوب عضوية معتمدة من مزارع جبال شياباس المكسيكية، صحي ولذيذ بنكهة المكسرات.',
      pricePerKg: 1150,
      category: 'مختص',
      roast: 'متوسط',
      notes: ['عضوي', 'مكسرات', 'حلو'],
      gradient: 'linear-gradient(135deg, #A99B7C 0%, #706A52 100%)',
      accent: '#A99768',
      badge: 'عضوي',
      image: 'mexican',
    },
    {
      id: 11,
      name: 'بن كوستاريكا',
      nameEn: 'Costa Rica Tarrazú',
      origin: 'كوستاريكا',
      tagline: 'حلو ومتوازن',
      description: 'بن من منطقة تارازو الشهيرة، حلاوة طبيعية وقوام نظيف.',
      pricePerKg: 990,
      category: 'مختص',
      roast: 'متوسط',
      notes: ['عسل', 'فانيليا', 'نظيف'],
      gradient: 'linear-gradient(135deg, #A99B7C 0%, #514B3B 100%)',
      accent: '#A99768',
      image: 'costarica',
    },
    {
      id: 12,
      name: 'إيطالي إسبريسو',
      nameEn: 'Italian Espresso',
      origin: 'مزيج إيطالي',
      tagline: 'كريما غنية',
      description: 'خلطة إيطالية كلاسيكية مصنوعة خصيصاً للإسبريسو، كريما ذهبية وقوام مخملي.',
      pricePerKg: 920,
      category: 'إسبريسو',
      roast: 'داكن',
      notes: ['كريمي', 'غني', 'إيطالي'],
      gradient: 'linear-gradient(135deg, #383328 0%, #17140F 100%)',
      accent: '#C4B383',
      image: 'italian',
    },
  ]

  const categories = ['الكل', 'عربي فاخر', 'إسبريسو', 'تركي', 'مختص']

  const getProductById = (id: number) => products.find(p => p.id === id)

  return { products, categories, getProductById }
}
